# Generated by Django 2.2.6 on 2019-12-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product1', models.CharField(choices=[('x', 'big'), ('y', 'normal'), ('z', 'small')], max_length=10)),
                ('product2', models.CharField(choices=[('x', 'big'), ('y', 'normal'), ('z', 'small')], max_length=10)),
                ('product3', models.CharField(choices=[('x', 'big'), ('y', 'normal'), ('z', 'small')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
        ),
    ]
