# Generated by Django 2.2.6 on 2019-12-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191216_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product3',
        ),
        migrations.AddField(
            model_name='category',
            name='TypeProduct',
            field=models.CharField(choices=[('x', 'quan'), ('y', 'ao'), ('z', 'giay')], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='nameProduct',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
